@AA = http://localhost:5133
@Username = Cody2
@Password = password
@Key = jScbw!u4LF0ljPzoixF4

###
GET {{AA}}/health
###
GET {{AA}}/users
###
GET {{AA}}/user/exact?account=Cody
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
POST {{AA}}/user?accountName=Admin
###
POST {{AA}}/user/signin
Content-Type: application/json

{
  "user": "{{Username}}",
  "pass": "{{Password}}"
}
###
GET {{AA}}/user/valid
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
GET {{AA}}/user/exists?user=cody
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
GET {{AA}}/user/guid
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
GET {{AA}}/user/role
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
GET {{AA}}/user/role/gt/0
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
GET {{AA}}/user/guid/get
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
GET {{AA}}/user/query?query=c
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
GET {{AA}}/user/count?account=Cody
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
#### Enables password change
PATCH {{AA}}/user 
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
Content-Type: application/json
{
  "user": "{{Username}}",
  "pass": "{{Password}}"
}
### Enables role change
PATCH {{AA}}/user/role?newRole=5
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
### Enables username change
PATCH {{AA}}/user/newname?guid=97e19267-0745-413e-be95-dacad076bfaa&newUser=Admin
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
DELETE {{AA}}/user/signout
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
DELETE {{AA}}/user/signout/global
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###

# Filter testing
GET {{AA}}/filters/stringis
Account-Auth-Account: {{Username}}
Account-Auth-ApiKey: {{Key}}
###
GET {{AA}}/ws/50453
###
